### ISSUE TITLE
Use .gitignore

### ISSUE THREAD

**Issue by krin-san** [frankymad/CheckIt#1]
При создании проекта на github есть вариант мгновенного добавления к проекту файла .gitignore под ЯП проекта. Это весьма полезно, т.к. есть файлы и директории, которые Xcode/AppCode создают для хранения настроек разработчика. Остальной команде не нужны эти файлы в репозитории, к тому же их заливка может приводить к конфликтам при операции merge.

Добавить .gitignore можно и вручную, уже после создания репозитория, взяв его по ссылке https://github.com/github/gitignore/blob/master/Objective-C.gitignore

**Comment by frankymad** [comment]
Done.
