### ISSUE TITLE
Rename the `description` property

### ISSUE THREAD

**Issue by krin-san** [frankymad/CheckIt#2]
Property с названием `description` не рекомендуется переопределять так, как [сделано у нас в CITask](https://github.com/frankymad/CheckIt/blob/develop/CheckIt/Classes/ViewControllers/CITask.h#L14). У корневого класса – NSObject – уже есть такой property. Часто его getter переопределяют, чтобы в логах видеть более читабельное описание объекта. Xcode говорит о переопределении property через warning.
Предлагаю выбрать другое название для property `description` и попробовать опцию `Refactor` в Xcode.

**Comment by frankymad** [comment]
Done.
