### ISSUE TITLE
Define property attributes

### ISSUE THREAD

**Issue by krin-san** [frankymad/CheckIt#3]
При объявлении следует, как минимум, указать два атрибута:
- **Atomicity** – `atomic` или `nonatomic`
- **Memory management** – `strong`, `weak` или `assign`

Таким образом, будут точно указаны самые важные из атрибутов. Например:

```
@property(nonatomic, strong) NSString *title;
@property(nonatomic, assign) BOOL checked;
```

**Comment by frankymad** [comment]
Done.
