### ISSUE TITLE
Use CITask in code

### ISSUE THREAD

**Issue by krin-san** [frankymad/CheckIt#4]
Нашёл одно несоответствие. Ты описал свой класс – `CITask` – для хранения данных о каждой отдельной задаче, однако в коде `CITaskTableViewController` [хранишь информацию в словаре](https://github.com/frankymad/CheckIt/blob/develop/CheckIt/Classes/ViewControllers/CITaskTableViewController.m#L22). Надо этот кусок переписать:
- добавить кастомный инициализатор в `CITask` для дальнейшего упрощения кода в контроллере:

```
- (instacetype)initWithTitle:(NSStirng *)title subtitle:(NSString *)subtitle completed:(BOOL)completed;
```
- переписать код во `-viewDidLoad`, чтобы массив хранил объекты типа `CITask`, а не словари:

```
self.tasks = @[
    [[CITask alloc] initWithTitle:@"A" subtitle:@"B" completed:NO],
    ...
];
```

**Comment by frankymad** [comment]
Fixed
