### ISSUE TITLE
Empty tasks

### ISSUE THREAD

**Issue by krin-san** [frankymad/CheckIt#5]
Получилось создать пустой таск, т.е. с пустым `title` и `description`. Это явная ошибка и такую ситуацию нужно отловить.
Как с ней поступить – другой вопрос. Можно или выдать alert, сказав, что создавать пустые таски нельзя, или просто не добавлять пустой таск (проигнорировать).
В текущей реализации второй вариант будет лучше. Не стоит лишний раз диктовать пользователю, как пользоваться приложением правильно.

**Comment by frankymad** [comment]
Fixed.
